'use client'

import { useState } from 'react'

const benefits = ['Visibilidad frente a una comunidad de trabajadores remotos', 'Promociona beneficios y ofertas especiales desde tu acceso Partner', 'Consulta estadísticas generales de visitas y escaneos', 'Posibilidad de recibir reservas y eventos a través de Workcofy']

export default function PartnerApplyPage() {
  const [sent, setSent] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError('')
    const data = Object.fromEntries(new FormData(event.currentTarget).entries())
    try { const response = await fetch('/api/partner-applications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSent(true) } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos enviar la postulación.') } finally { setLoading(false) }
  }
  return <main className="mx-auto max-w-6xl px-4 py-10 md:px-8 md:py-16"><div className="grid gap-10 md:grid-cols-[0.9fr_1.1fr] md:items-start"><section><img src="/icons/logo-partner.png" alt="Workcofy Partner" className="h-16 w-16 object-contain" /><p className="mt-5 text-xs font-bold uppercase tracking-[0.25em] text-gray-400">Workcofy Partners</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight text-gray-950 md:text-5xl">Haz que tu local sea parte de la red.</h1><p className="mt-5 max-w-lg text-lg leading-relaxed text-gray-600">Conecta tu espacio con personas que buscan lugares cómodos para trabajar, reunirse y socializar.</p><ul className="mt-8 space-y-4">{benefits.map((benefit) => <li key={benefit} className="flex gap-3 text-sm font-medium text-gray-700"><span className="mt-1 h-2.5 w-2.5 flex-none rounded-full bg-workcofy-yellow" />{benefit}</li>)}</ul><a href="/partners" className="mt-8 inline-block text-sm font-bold underline">¿Ya eres Partner? Ingresa a tu panel</a></section><section className="rounded-3xl border border-gray-200 bg-white p-5 shadow-sm md:p-8"><h2 className="text-2xl font-extrabold">Postula tu local</h2>{sent ? <div className="mt-6 rounded-2xl bg-green-50 p-5 text-sm text-green-800"><p className="font-bold">¡Gracias! Recibimos tu postulación.</p><p className="mt-2">Revisaremos la información y nos pondremos en contacto contigo.</p></div> : <form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Nombre del local<input required name="businessName" placeholder="Ej. Café Central" /></label><label>Nombre de contacto<input required name="contactName" placeholder="Tu nombre" /></label><label>Correo<input required type="email" name="email" placeholder="correo@local.com" /></label><label>Teléfono / WhatsApp<input name="phone" placeholder="+51 999 999 999" /></label><label>País<input required name="country" placeholder="Perú" /></label><label>Ciudad<input required name="city" placeholder="Lima" /></label><label className="sm:col-span-2">Dirección<input required name="address" placeholder="Dirección del local" /></label><label className="sm:col-span-2">Tipo de espacio<select required name="spaceType" defaultValue=""><option value="" disabled>Selecciona una opción</option><option>Café Workfriendly</option><option>Café Coworking</option><option>Coworking</option><option>Lobby Café</option><option>Otro</option></select></label><label className="sm:col-span-2">Cuéntanos sobre tu local<textarea name="message" rows={3} placeholder="Wi-Fi, enchufes, promociones o cualquier detalle útil" /></label>{error && <p className="sm:col-span-2 text-sm font-semibold text-red-600">{error}</p>}<button disabled={loading} className="sm:col-span-2 rounded-full bg-black px-5 py-3.5 text-sm font-bold text-white disabled:opacity-50">{loading ? 'Enviando…' : 'Enviar postulación'}</button></form>}</section></div></main>
}
