// Full country list for the registration form's country selector —
// deliberately separate from lib/countries.ts's COUNTRY_OPTIONS, which is
// scoped to where Workcofy currently operates (Perú/Chile) for the
// discovery filters. This one is "where a signing-up user might be from,"
// a different concern with a much longer value set.
export const ALL_COUNTRIES: { value: string; label: string }[] = [
  { value: 'af', label: 'Afganistán' },
  { value: 'za', label: 'Sudáfrica' },
  { value: 'al', label: 'Albania' },
  { value: 'de', label: 'Alemania' },
  { value: 'ad', label: 'Andorra' },
  { value: 'ao', label: 'Angola' },
  { value: 'sa', label: 'Arabia Saudita' },
  { value: 'dz', label: 'Argelia' },
  { value: 'ar', label: 'Argentina' },
  { value: 'am', label: 'Armenia' },
  { value: 'au', label: 'Australia' },
  { value: 'at', label: 'Austria' },
  { value: 'az', label: 'Azerbaiyán' },
  { value: 'bs', label: 'Bahamas' },
  { value: 'bd', label: 'Bangladés' },
  { value: 'bb', label: 'Barbados' },
  { value: 'bh', label: 'Baréin' },
  { value: 'be', label: 'Bélgica' },
  { value: 'bz', label: 'Belice' },
  { value: 'bj', label: 'Benín' },
  { value: 'by', label: 'Bielorrusia' },
  { value: 'mm', label: 'Birmania' },
  { value: 'bo', label: 'Bolivia' },
  { value: 'ba', label: 'Bosnia y Herzegovina' },
  { value: 'bw', label: 'Botsuana' },
  { value: 'br', label: 'Brasil' },
  { value: 'bn', label: 'Brunéi' },
  { value: 'bg', label: 'Bulgaria' },
  { value: 'bf', label: 'Burkina Faso' },
  { value: 'bi', label: 'Burundi' },
  { value: 'bt', label: 'Bután' },
  { value: 'cv', label: 'Cabo Verde' },
  { value: 'kh', label: 'Camboya' },
  { value: 'cm', label: 'Camerún' },
  { value: 'ca', label: 'Canadá' },
  { value: 'qa', label: 'Catar' },
  { value: 'td', label: 'Chad' },
  { value: 'cl', label: 'Chile' },
  { value: 'cn', label: 'China' },
  { value: 'cy', label: 'Chipre' },
  { value: 'co', label: 'Colombia' },
  { value: 'km', label: 'Comoras' },
  { value: 'kp', label: 'Corea del Norte' },
  { value: 'kr', label: 'Corea del Sur' },
  { value: 'ci', label: 'Costa de Marfil' },
  { value: 'cr', label: 'Costa Rica' },
  { value: 'hr', label: 'Croacia' },
  { value: 'cu', label: 'Cuba' },
  { value: 'dk', label: 'Dinamarca' },
  { value: 'dm', label: 'Dominica' },
  { value: 'ec', label: 'Ecuador' },
  { value: 'eg', label: 'Egipto' },
  { value: 'sv', label: 'El Salvador' },
  { value: 'ae', label: 'Emiratos Árabes Unidos' },
  { value: 'er', label: 'Eritrea' },
  { value: 'sk', label: 'Eslovaquia' },
  { value: 'si', label: 'Eslovenia' },
  { value: 'es', label: 'España' },
  { value: 'us', label: 'Estados Unidos' },
  { value: 'ee', label: 'Estonia' },
  { value: 'sz', label: 'Esuatini' },
  { value: 'et', label: 'Etiopía' },
  { value: 'ph', label: 'Filipinas' },
  { value: 'fi', label: 'Finlandia' },
  { value: 'fj', label: 'Fiyi' },
  { value: 'fr', label: 'Francia' },
  { value: 'ga', label: 'Gabón' },
  { value: 'gm', label: 'Gambia' },
  { value: 'ge', label: 'Georgia' },
  { value: 'gh', label: 'Ghana' },
  { value: 'gd', label: 'Granada' },
  { value: 'gr', label: 'Grecia' },
  { value: 'gt', label: 'Guatemala' },
  { value: 'gy', label: 'Guyana' },
  { value: 'gn', label: 'Guinea' },
  { value: 'gw', label: 'Guinea-Bisáu' },
  { value: 'gq', label: 'Guinea Ecuatorial' },
  { value: 'ht', label: 'Haití' },
  { value: 'hn', label: 'Honduras' },
  { value: 'hu', label: 'Hungría' },
  { value: 'in', label: 'India' },
  { value: 'id', label: 'Indonesia' },
  { value: 'iq', label: 'Irak' },
  { value: 'ir', label: 'Irán' },
  { value: 'ie', label: 'Irlanda' },
  { value: 'is', label: 'Islandia' },
  { value: 'sb', label: 'Islas Salomón' },
  { value: 'il', label: 'Israel' },
  { value: 'it', label: 'Italia' },
  { value: 'jm', label: 'Jamaica' },
  { value: 'jp', label: 'Japón' },
  { value: 'jo', label: 'Jordania' },
  { value: 'kz', label: 'Kazajistán' },
  { value: 'ke', label: 'Kenia' },
  { value: 'kg', label: 'Kirguistán' },
  { value: 'ki', label: 'Kiribati' },
  { value: 'kw', label: 'Kuwait' },
  { value: 'la', label: 'Laos' },
  { value: 'ls', label: 'Lesoto' },
  { value: 'lv', label: 'Letonia' },
  { value: 'lb', label: 'Líbano' },
  { value: 'lr', label: 'Liberia' },
  { value: 'ly', label: 'Libia' },
  { value: 'li', label: 'Liechtenstein' },
  { value: 'lt', label: 'Lituania' },
  { value: 'lu', label: 'Luxemburgo' },
  { value: 'mk', label: 'Macedonia del Norte' },
  { value: 'mg', label: 'Madagascar' },
  { value: 'my', label: 'Malasia' },
  { value: 'mw', label: 'Malaui' },
  { value: 'mv', label: 'Maldivas' },
  { value: 'ml', label: 'Malí' },
  { value: 'mt', label: 'Malta' },
  { value: 'ma', label: 'Marruecos' },
  { value: 'mu', label: 'Mauricio' },
  { value: 'mr', label: 'Mauritania' },
  { value: 'mx', label: 'México' },
  { value: 'fm', label: 'Micronesia' },
  { value: 'md', label: 'Moldavia' },
  { value: 'mc', label: 'Mónaco' },
  { value: 'mn', label: 'Mongolia' },
  { value: 'me', label: 'Montenegro' },
  { value: 'mz', label: 'Mozambique' },
  { value: 'na', label: 'Namibia' },
  { value: 'nr', label: 'Nauru' },
  { value: 'np', label: 'Nepal' },
  { value: 'ni', label: 'Nicaragua' },
  { value: 'ne', label: 'Níger' },
  { value: 'ng', label: 'Nigeria' },
  { value: 'no', label: 'Noruega' },
  { value: 'nz', label: 'Nueva Zelanda' },
  { value: 'om', label: 'Omán' },
  { value: 'nl', label: 'Países Bajos' },
  { value: 'pk', label: 'Pakistán' },
  { value: 'pw', label: 'Palaos' },
  { value: 'pa', label: 'Panamá' },
  { value: 'pg', label: 'Papúa Nueva Guinea' },
  { value: 'py', label: 'Paraguay' },
  { value: 'pe', label: 'Perú' },
  { value: 'pl', label: 'Polonia' },
  { value: 'pt', label: 'Portugal' },
  { value: 'gb', label: 'Reino Unido' },
  { value: 'cf', label: 'República Centroafricana' },
  { value: 'cz', label: 'República Checa' },
  { value: 'cg', label: 'República del Congo' },
  { value: 'cd', label: 'República Democrática del Congo' },
  { value: 'do', label: 'República Dominicana' },
  { value: 'rw', label: 'Ruanda' },
  { value: 'ro', label: 'Rumanía' },
  { value: 'ru', label: 'Rusia' },
  { value: 'ws', label: 'Samoa' },
  { value: 'kn', label: 'San Cristóbal y Nieves' },
  { value: 'sm', label: 'San Marino' },
  { value: 'vc', label: 'San Vicente y las Granadinas' },
  { value: 'lc', label: 'Santa Lucía' },
  { value: 'st', label: 'Santo Tomé y Príncipe' },
  { value: 'sn', label: 'Senegal' },
  { value: 'rs', label: 'Serbia' },
  { value: 'sc', label: 'Seychelles' },
  { value: 'sl', label: 'Sierra Leona' },
  { value: 'sg', label: 'Singapur' },
  { value: 'sy', label: 'Siria' },
  { value: 'so', label: 'Somalia' },
  { value: 'lk', label: 'Sri Lanka' },
  { value: 'se', label: 'Suecia' },
  { value: 'ch', label: 'Suiza' },
  { value: 'sr', label: 'Surinam' },
  { value: 'th', label: 'Tailandia' },
  { value: 'tz', label: 'Tanzania' },
  { value: 'tj', label: 'Tayikistán' },
  { value: 'tl', label: 'Timor Oriental' },
  { value: 'tg', label: 'Togo' },
  { value: 'to', label: 'Tonga' },
  { value: 'tt', label: 'Trinidad y Tobago' },
  { value: 'tn', label: 'Túnez' },
  { value: 'tm', label: 'Turkmenistán' },
  { value: 'tr', label: 'Turquía' },
  { value: 'tv', label: 'Tuvalu' },
  { value: 'ua', label: 'Ucrania' },
  { value: 'ug', label: 'Uganda' },
  { value: 'uy', label: 'Uruguay' },
  { value: 'uz', label: 'Uzbekistán' },
  { value: 'vu', label: 'Vanuatu' },
  { value: 've', label: 'Venezuela' },
  { value: 'vn', label: 'Vietnam' },
  { value: 'ye', label: 'Yemen' },
  { value: 'dj', label: 'Yibuti' },
  { value: 'zm', label: 'Zambia' },
  { value: 'zw', label: 'Zimbabue' },
].sort((a, b) => a.label.localeCompare(b.label, 'es'))
