import type { CourseCategory, CourseLanguage, CourseLevel, CoursePrice, CourseTool } from './constants'
import type { ProfessionValue } from '@/lib/professions'

export interface CourseSeed {
  title: string
  provider: string
  category: CourseCategory
  area?: ProfessionValue | null
  tool?: CourseTool | null
  level: CourseLevel
  duration_text?: string | null
  price: CoursePrice
  price_text?: string | null
  has_certificate: boolean
  language: CourseLanguage
  url: string
  summary: string
  tags: string[]
  featured?: boolean
  last_verified_at: string
}

// Official-provider AI courses and certifications, researched and URL-verified
// on 2026-09-05 (design spec §4). Edit in Supabase's Table Editor after
// seeding; re-running `npm run seed:courses` upserts by slug. Exam prices are
// approximate US list prices — check local pricing before relying on them.
export const COURSE_SEED_CATALOG: CourseSeed[] = [
  {
    title: 'Google AI Essentials',
    provider: 'Google',
    category: 'ia_desde_cero',
    level: 'principiante',
    duration_text: 'menos de 10 horas',
    price: 'pago',
    price_text: 'Suscripción Coursera (USD 49/mes aprox.); prueba gratuita de 7 días',
    has_certificate: true,
    language: 'multi',
    url: 'https://www.coursera.org/specializations/ai-essentials-google',
    summary: 'Curso de Google para usar IA generativa en tareas de trabajo cotidianas: redactar prompts, generar contenido e ideas y aplicar IA de forma responsable. Disponible con contenido completo en español.',
    tags: ['google', 'ia generativa', 'prompts', 'coursera', 'español disponible'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Beginner: Introduction to Generative AI (ruta de aprendizaje)',
    provider: 'Google Cloud',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://www.skills.google/paths/118',
    summary: 'Ruta de microcursos de Google Cloud que introduce la IA generativa, los modelos de lenguaje grandes y la IA responsable, sin requerir código. Otorga insignias digitales al completar cada curso.',
    tags: ['google cloud', 'ia generativa', 'llm', 'insignia'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introduction to Generative AI',
    provider: 'Google Cloud',
    category: 'ia_desde_cero',
    level: 'principiante',
    duration_text: '45 minutos aprox.',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://www.skills.google/course_templates/536',
    summary: 'Microcurso introductorio que explica qué es la IA generativa, cómo se usa y en qué se diferencia del aprendizaje automático tradicional.',
    tags: ['google cloud', 'ia generativa', 'microcurso'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introduction to Responsible AI – Español',
    provider: 'Google Cloud',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    price_text: 'Auditar gratis; certificado de Coursera de pago',
    has_certificate: true,
    language: 'es',
    url: 'https://www.coursera.org/learn/introduction-to-responsible-ai-es',
    summary: 'Versión en español del microcurso de Google Cloud sobre IA responsable: qué es, por qué es importante y cómo Google la implementa en sus productos.',
    tags: ['google cloud', 'ia responsable', 'coursera', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Fluency de IA: explore la inteligencia artificial en su idioma',
    provider: 'Microsoft',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/paths/ai-fluency/',
    summary: 'Ruta de aprendizaje de Microsoft Learn que explica los conceptos básicos de la IA y la IA generativa en lenguaje sencillo, incluyendo cómo empezar a usar Microsoft Copilot.',
    tags: ['microsoft', 'ia generativa', 'copilot', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introducción a la inteligencia artificial generativa: exploración de los conceptos básicos',
    provider: 'Microsoft',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/modules/intro-generative-ai-explore-basics/',
    summary: 'Módulo de Microsoft Learn que cubre los fundamentos de la IA generativa y sus aplicaciones, e introduce Microsoft Copilot y las habilidades básicas para usar modelos de lenguaje de forma eficaz y responsable.',
    tags: ['microsoft', 'ia generativa', 'copilot', 'español'],
    featured: true,
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introducción a las aplicaciones y agentes de inteligencia artificial en Azure',
    provider: 'Microsoft',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/paths/get-started-ai-apps-agents/',
    summary: 'Ruta de aprendizaje en español que presenta los conceptos esenciales de IA, aprendizaje automático, IA generativa y agentes, con foco en los servicios de Azure. Es la base de la certificación AI-900.',
    tags: ['microsoft', 'azure', 'ai-900', 'agentes', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Career Essentials in Generative AI by Microsoft and LinkedIn',
    provider: 'Microsoft + LinkedIn Learning',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://www.linkedin.com/learning/paths/career-essentials-in-generative-ai-by-microsoft-and-linkedin',
    summary: 'Ruta gratuita de LinkedIn Learning creada con Microsoft que cubre los conceptos básicos de la IA generativa, sus usos en el trabajo y consideraciones éticas. Otorga un certificado profesional al finalizar.',
    tags: ['microsoft', 'linkedin', 'ia generativa', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introduction to Generative AI – Art of the Possible',
    provider: 'AWS',
    category: 'ia_desde_cero',
    level: 'principiante',
    duration_text: '1 hora',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://skillbuilder.aws/learn/ZEVZZ1D4AS/introduction-to-generative-ai--art-of-the-possible/Y7MTGJCW1U',
    summary: 'Curso digital gratuito de AWS Skill Builder que explica qué es la IA generativa, sus casos de uso en negocios y sus riesgos, sin requerir código. Forma parte de la serie para tomadores de decisiones.',
    tags: ['aws', 'ia generativa', 'skill builder', 'sin código'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Artificial Intelligence Fundamentals (IBM SkillsBuild)',
    provider: 'IBM',
    category: 'ia_desde_cero',
    level: 'principiante',
    duration_text: '10 horas aprox.',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://www.ibm.com/training/badge/artificial-intelligence-fundamentals',
    summary: 'Plan de aprendizaje gratuito de IBM SkillsBuild sobre historia y conceptos de IA, aprendizaje automático, procesamiento de lenguaje natural, visión por computadora y ética de la IA. Otorga una insignia digital de IBM.',
    tags: ['ibm', 'skillsbuild', 'fundamentos', 'insignia'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Generative AI Explained',
    provider: 'NVIDIA',
    category: 'ia_desde_cero',
    level: 'principiante',
    duration_text: '2 horas',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-FX-07+V1',
    summary: 'Curso gratuito del NVIDIA Deep Learning Institute, sin código, que explica los conceptos, aplicaciones, retos y oportunidades de la IA generativa. Incluye certificado de finalización.',
    tags: ['nvidia', 'dli', 'ia generativa', 'sin código'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Agentic AI Explained',
    provider: 'NVIDIA',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-FX-39+V1',
    summary: 'Curso introductorio gratuito del NVIDIA DLI que explica qué son los agentes de IA, cómo se diferencian de los chatbots y qué casos de uso habilitan.',
    tags: ['nvidia', 'dli', 'agentes', 'ia agéntica'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introducción a la inteligencia artificial (trail)',
    provider: 'Salesforce Trailhead',
    category: 'ia_desde_cero',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://trailhead.salesforce.com/es-MX/content/learn/trails/get-started-with-ai-data',
    summary: 'Trail de Trailhead en español que enseña los fundamentos de la IA y la IA generativa, la tecnología que las hace posibles y cómo crearlas de forma responsable. Otorga insignias por módulo.',
    tags: ['salesforce', 'trailhead', 'fundamentos', 'español', 'insignia'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AI Fluency: Framework & Foundations',
    provider: 'Anthropic',
    category: 'ia_desde_cero',
    level: 'principiante',
    duration_text: '3-4 horas',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://anthropic.skilljar.com/ai-fluency-framework-foundations',
    summary: 'Curso de Anthropic Academy que enseña el marco de las 4D (delegación, descripción, discernimiento y diligencia) para colaborar con la IA de forma eficaz, ética y segura. Incluye certificado gratuito.',
    tags: ['anthropic', 'ai fluency', 'colaboración con ia', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AI Capabilities and Limitations',
    provider: 'Anthropic',
    category: 'ia_desde_cero',
    level: 'principiante',
    duration_text: '3,5 horas',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://academy.claude.com/courses/ai-capabilities-and-limitations',
    summary: 'Curso de Claude Academy que explica qué pueden y qué no pueden hacer los modelos de IA actuales, para tomar mejores decisiones sobre cuándo y cómo usarlos.',
    tags: ['anthropic', 'claude academy', 'capacidades', 'limitaciones'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AI for Marketing',
    provider: 'HubSpot Academy',
    category: 'ia_por_profesion',
    area: 'marketing',
    level: 'principiante',
    duration_text: '3 horas aprox.',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://academy.hubspot.com/courses/AI-for-Marketers',
    summary: 'Curso gratuito de HubSpot Academy (6 lecciones, 15 videos) sobre cómo usar IA en creación de contenido, personalización de la experiencia del cliente y redacción de prompts para marketing, con enfoque en uso ético.',
    tags: ['hubspot', 'marketing', 'prompts', 'contenido'],
    featured: true,
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AI for Sales',
    provider: 'HubSpot Academy',
    category: 'ia_por_profesion',
    area: 'ventas',
    level: 'principiante',
    duration_text: '36 minutos',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://academy.hubspot.com/courses/ai-for-sales',
    summary: 'Curso corto de HubSpot Academy (2 lecciones, 7 videos) sobre cómo aplicar herramientas de IA para calificar leads, priorizar oportunidades y mejorar la productividad comercial.',
    tags: ['hubspot', 'ventas', 'leads', 'productividad'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Generative AI for Marketers',
    provider: 'Meta',
    category: 'ia_por_profesion',
    area: 'marketing',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://www.facebookblueprint.com/student/path/628781-generative-ai-for-marketers',
    summary: 'Ruta de Meta Blueprint sobre cómo usar las herramientas de IA generativa de Meta para escribir prompts, crear y refinar creatividades publicitarias y ganar productividad en marketing.',
    tags: ['meta', 'blueprint', 'marketing', 'anuncios', 'ia generativa'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Curso de Meta AI: Introducción a la IA generativa y las indicaciones',
    provider: 'Meta',
    category: 'ia_por_profesion',
    area: 'marketing',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'multi',
    url: 'https://www.facebook.com/business/learn/lessons/gen-ai',
    summary: 'Lección de Meta para empresas que introduce la IA generativa y la redacción de indicaciones (prompts) aplicadas a la creación de contenido y anuncios. La página se muestra en español según la región.',
    tags: ['meta', 'ia generativa', 'prompts', 'pymes', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Generative AI Learning Plan for Decision Makers',
    provider: 'AWS',
    category: 'ia_por_profesion',
    area: 'emprendimiento',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://skillbuilder.aws/learning-plan/STDH6NGPH7/generative-ai-learning-plan-for-decision-makers/MHMHDAWQJY',
    summary: 'Plan de tres cursos de AWS Skill Builder para líderes y dueños de negocio: qué es la IA generativa, cómo planificar un proyecto y cómo preparar a la organización, sin requerir código.',
    tags: ['aws', 'líderes', 'estrategia', 'ia generativa', 'sin código'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Comprender los fundamentos de la IA generativa para los líderes empresariales',
    provider: 'Microsoft',
    category: 'ia_por_profesion',
    area: 'emprendimiento',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/modules/understand-foundations-generative-ai-business-leaders/',
    summary: 'Módulo de Microsoft Learn para líderes y emprendedores que explica conceptos, tecnologías y soluciones de IA generativa (Copilot, Azure AI, agentes), con escenarios reales, costos y adopción responsable.',
    tags: ['microsoft', 'líderes', 'estrategia', 'copilot', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Innova con la Inteligencia Artificial de Google Cloud',
    provider: 'Google Cloud',
    category: 'ia_por_profesion',
    area: 'otros',
    level: 'principiante',
    price: 'gratis',
    price_text: 'Auditar gratis; certificado de Coursera de pago',
    has_certificate: true,
    language: 'es',
    url: 'https://www.coursera.org/learn/innovating-with-google-cloud-artificial-intelligence-es',
    summary: 'Curso en español de Google Cloud orientado a perfiles de negocio: cómo la IA y el aprendizaje automático generan valor empresarial y qué soluciones de Google Cloud aplican a distintos casos.',
    tags: ['google cloud', 'negocio', 'coursera', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introduction to AI and Machine Learning on Google Cloud – Español',
    provider: 'Google Cloud',
    category: 'ia_por_profesion',
    area: 'datos',
    level: 'intermedio',
    price: 'gratis',
    price_text: 'Auditar gratis; certificado de Coursera de pago',
    has_certificate: true,
    language: 'es',
    url: 'https://www.coursera.org/learn/introduction-to-ai-and-machine-learning-on-gc---es',
    summary: 'Curso en español de Google Cloud que recorre las capas de IA y aprendizaje automático en la plataforma, desde la infraestructura de datos hasta las soluciones de IA generativa.',
    tags: ['google cloud', 'machine learning', 'datos', 'coursera', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Generative AI for Educators with Gemini',
    provider: 'Google for Education',
    category: 'ia_por_profesion',
    area: 'educacion',
    level: 'principiante',
    duration_text: '2 horas',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://edu.exceedlms.com/student/path/1787126-generative-ai-for-educators-with-gemini',
    summary: 'Curso gratuito de Google for Education, creado con MIT RAISE, para que docentes usen Gemini y otras herramientas de IA generativa para personalizar la enseñanza y ahorrar tiempo en tareas administrativas.',
    tags: ['google', 'educación', 'docentes', 'gemini', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introducción a la inteligencia artificial generativa para instructores',
    provider: 'Microsoft',
    category: 'ia_por_profesion',
    area: 'educacion',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/paths/intro-generative-ai-for-trainers/',
    summary: 'Ruta de Microsoft Learn para docentes y formadores sobre cómo usar Microsoft Copilot y generadores de imágenes para crear materiales educativos atractivos.',
    tags: ['microsoft', 'educación', 'docentes', 'copilot', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AI Fluency for Educators',
    provider: 'Anthropic',
    category: 'ia_por_profesion',
    area: 'educacion',
    level: 'principiante',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://anthropic.skilljar.com/ai-fluency-for-educators',
    summary: 'Curso de Anthropic Academy que adapta el marco de AI Fluency al aula: cómo integrar la IA en la enseñanza, diseñar actividades y guiar a estudiantes en su uso responsable.',
    tags: ['anthropic', 'educación', 'docentes', 'ai fluency'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Building with the Claude API',
    provider: 'Anthropic',
    category: 'ia_por_profesion',
    area: 'ingenieria',
    level: 'intermedio',
    duration_text: '8 horas aprox.',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://anthropic.skilljar.com/claude-with-the-anthropic-api',
    summary: 'Curso completo de Anthropic Academy para desarrolladores: uso de la API de Claude, ingeniería de prompts, uso de herramientas, RAG y patrones para construir aplicaciones.',
    tags: ['anthropic', 'claude', 'api', 'desarrollo', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AI Foundations',
    provider: 'OpenAI',
    category: 'herramientas',
    tool: 'chatgpt',
    level: 'principiante',
    duration_text: '1 hora aprox.',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://academy.openai.com/public/courses/ai-foundations-juzjs',
    summary: 'Curso de OpenAI Academy que introduce la IA, los modelos de lenguaje y ChatGPT, y crea hábitos básicos: dar contexto, redactar prompts claros, evaluar resultados y usar la IA con responsabilidad. Otorga certificado de finalización.',
    tags: ['openai', 'chatgpt', 'fundamentos', 'prompts', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Applied AI Foundations',
    provider: 'OpenAI',
    category: 'herramientas',
    tool: 'chatgpt',
    level: 'intermedio',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://academy.openai.com/public/courses/applied-ai-foundations-hgk7r',
    summary: 'Curso de OpenAI Academy para convertir trabajo repetitivo en procesos sistemáticos con ChatGPT: identificar dónde ayuda la IA y establecer puntos de control de calidad.',
    tags: ['openai', 'chatgpt', 'productividad', 'procesos', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Agents and Workflows',
    provider: 'OpenAI',
    category: 'herramientas',
    tool: 'automatizacion',
    level: 'intermedio',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://academy.openai.com/public/courses/agents-and-workflows-bieml',
    summary: 'Curso de OpenAI Academy sobre cómo dirigir agentes de IA en tareas estructuradas: definir contexto, resultados esperados, límites y refinar flujos de trabajo.',
    tags: ['openai', 'agentes', 'flujos de trabajo', 'automatización', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'ChatGPT for Work Webinars',
    provider: 'OpenAI',
    category: 'herramientas',
    tool: 'chatgpt',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://academy.openai.com/pages/chatgpt-for-work-webinars-1y07zs',
    summary: 'Serie de webinars de OpenAI Academy (ChatGPT 101, 102 y sesiones temáticas) sobre capacidades de ChatGPT y casos de uso prácticos en el trabajo, con sesiones grabadas y en vivo.',
    tags: ['openai', 'chatgpt', 'webinar', 'trabajo'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'ChatGPT Prompt Engineering for Developers',
    provider: 'DeepLearning.AI + OpenAI',
    category: 'herramientas',
    tool: 'chatgpt',
    level: 'intermedio',
    duration_text: '1 hora aprox.',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://www.deeplearning.ai/courses/chatgpt-prompt-eng',
    summary: 'Curso corto creado con OpenAI sobre buenas prácticas de prompting y uso de LLM para resumir, inferir, transformar y expandir texto mediante la API.',
    tags: ['deeplearning.ai', 'openai', 'prompts', 'api'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Claude 101',
    provider: 'Anthropic',
    category: 'herramientas',
    tool: 'claude',
    level: 'principiante',
    duration_text: '1 hora aprox.',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://anthropic.skilljar.com/claude-101',
    summary: 'Curso introductorio de Anthropic Academy sobre cómo usar Claude en flujos de trabajo cotidianos: conversaciones, proyectos, archivos y buenas prácticas de prompting. Incluye certificado gratuito.',
    tags: ['anthropic', 'claude', 'introducción', 'certificado'],
    featured: true,
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Claude Code 101',
    provider: 'Anthropic',
    category: 'herramientas',
    tool: 'claude',
    level: 'intermedio',
    duration_text: '1 hora aprox.',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://anthropic.skilljar.com/claude-code-101',
    summary: 'Curso de Anthropic Academy que introduce Claude Code, el asistente de programación agéntico en la terminal: instalación, comandos básicos y primeros flujos de trabajo.',
    tags: ['anthropic', 'claude code', 'desarrollo', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Claude Code in Action',
    provider: 'Anthropic',
    category: 'herramientas',
    tool: 'claude',
    level: 'intermedio',
    duration_text: '2 horas aprox.',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://anthropic.skilljar.com/claude-code-in-action',
    summary: 'Curso de Anthropic Academy sobre uso avanzado de Claude Code: configuración, integración con MCP y creación de Skills reutilizables para automatizar tareas de desarrollo.',
    tags: ['anthropic', 'claude code', 'skills', 'mcp', 'certificado'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Agent Skills with Anthropic',
    provider: 'DeepLearning.AI + Anthropic',
    category: 'herramientas',
    tool: 'claude',
    level: 'intermedio',
    duration_text: '1 hora aprox.',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://www.deeplearning.ai/courses/agent-skills-with-anthropic',
    summary: 'Curso corto creado con Anthropic sobre cómo diseñar y empaquetar Skills reutilizables que los agentes de Claude aplican automáticamente a las tareas adecuadas.',
    tags: ['deeplearning.ai', 'anthropic', 'agentes', 'skills'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Google Prompting Essentials',
    provider: 'Google',
    category: 'herramientas',
    tool: 'productividad',
    level: 'principiante',
    duration_text: 'menos de 6 horas',
    price: 'pago',
    price_text: 'Suscripción Coursera (USD 49/mes aprox.); prueba gratuita de 7 días',
    has_certificate: true,
    language: 'multi',
    url: 'https://www.coursera.org/specializations/prompting-essentials-google',
    summary: 'Programa de Google que enseña un método de 5 pasos para escribir prompts eficaces y reutilizables que funcionan con distintas herramientas de IA. Otorga certificado de Google.',
    tags: ['google', 'prompts', 'coursera', 'productividad'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Introduction to Google Workspace with Gemini',
    provider: 'Google Cloud',
    category: 'herramientas',
    tool: 'gemini',
    level: 'principiante',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://www.skills.google/course_templates/888',
    summary: 'Microcurso de Google Skills que presenta las funciones de Gemini en Gmail, Docs, Sheets, Slides y Meet para redactar, resumir y analizar información.',
    tags: ['google', 'gemini', 'workspace', 'productividad'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AI Boost Bootcamp: How to Use Gemini at Work 101',
    provider: 'Google Cloud',
    category: 'herramientas',
    tool: 'gemini',
    level: 'principiante',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://www.skills.google/course_templates/1674',
    summary: 'Curso de Google Skills con ejercicios prácticos para usar la app Gemini en tareas de trabajo: investigación, redacción, análisis y organización.',
    tags: ['google', 'gemini', 'bootcamp', 'productividad'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Large Multimodal Model Prompting with Gemini',
    provider: 'DeepLearning.AI + Google Cloud',
    category: 'herramientas',
    tool: 'gemini',
    level: 'intermedio',
    duration_text: '1,5 horas aprox.',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://www.deeplearning.ai/courses/large-multimodal-model-prompting-with-gemini',
    summary: 'Curso corto creado con Google Cloud sobre buenas prácticas de prompting multimodal (texto, imagen, video) con los modelos Gemini.',
    tags: ['deeplearning.ai', 'google', 'gemini', 'multimodal', 'prompts'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Fluidez de IA: Introducción a Microsoft Copilot',
    provider: 'Microsoft',
    category: 'herramientas',
    tool: 'copilot',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/modules/get-started-with-copilot/',
    summary: 'Módulo de Microsoft Learn en español para empezar a usar Microsoft Copilot: qué es, cómo acceder y cómo escribir buenas indicaciones para tareas diarias.',
    tags: ['microsoft', 'copilot', 'introducción', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Redactar, analizar y presentar con Microsoft Copilot (MS-4018)',
    provider: 'Microsoft',
    category: 'herramientas',
    tool: 'copilot',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/paths/draft-analyze-present-microsoft-365-copilot/',
    summary: 'Ruta práctica de Microsoft Learn en español para usar Microsoft 365 Copilot en Word, Excel, PowerPoint, Outlook y Teams. No requiere experiencia previa con IA.',
    tags: ['microsoft', 'copilot', 'microsoft 365', 'productividad', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Capacitar a los empleados con casos de uso de Microsoft 365 Copilot',
    provider: 'Microsoft',
    category: 'herramientas',
    tool: 'copilot',
    level: 'intermedio',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/paths/empower-workforce-copilot-use-cases/',
    summary: 'Ruta de Microsoft Learn con ejercicios de casos de uso de Microsoft 365 Copilot por rol: ejecutivos, ventas, marketing, finanzas, TI, recursos humanos y operaciones.',
    tags: ['microsoft', 'copilot', 'casos de uso', 'ventas', 'marketing', 'finanzas', 'rrhh', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Crear agentes en Microsoft Copilot Studio',
    provider: 'Microsoft',
    category: 'herramientas',
    tool: 'automatizacion',
    level: 'intermedio',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/training/paths/create-extend-custom-copilots-microsoft-copilot-studio/',
    summary: 'Ruta de Microsoft Learn en español para crear, extender y publicar agentes personalizados con Copilot Studio sin necesidad de programar.',
    tags: ['microsoft', 'copilot studio', 'agentes', 'automatización', 'sin código', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Prompt Fundamentals',
    provider: 'Salesforce Trailhead',
    category: 'herramientas',
    tool: 'productividad',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://trailhead.salesforce.com/content/learn/modules/prompt-fundamentals',
    summary: 'Módulo gratuito de Trailhead sobre cómo escribir prompts eficaces para herramientas de IA generativa, con técnicas aplicables a cualquier asistente.',
    tags: ['salesforce', 'trailhead', 'prompts', 'productividad'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Prepararse para Agentforce (trail)',
    provider: 'Salesforce Trailhead',
    category: 'herramientas',
    tool: 'automatizacion',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'es',
    url: 'https://trailhead.salesforce.com/es-MX/content/learn/trails/get-ready-for-agentforce',
    summary: 'Trail de Trailhead en español sobre cómo los agentes de IA de Agentforce pueden transformar el trabajo, cómo encajan en los objetivos del negocio y cómo lanzar un primer agente.',
    tags: ['salesforce', 'agentforce', 'agentes', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Microsoft Certified: Azure AI Fundamentals (AI-900)',
    provider: 'Microsoft',
    category: 'certificaciones',
    level: 'principiante',
    price: 'pago',
    price_text: 'USD 99 aprox. el examen (varía por país); preparación gratuita en Microsoft Learn',
    has_certificate: true,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/credentials/certifications/azure-ai-fundamentals/',
    summary: 'Certificación de nivel básico que valida conocimientos de aprendizaje automático, IA generativa y servicios de IA de Azure. No requiere experiencia técnica; el examen está disponible en español.',
    tags: ['microsoft', 'azure', 'ai-900', 'certificación', 'español'],
    featured: true,
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Microsoft Certified: Azure AI Engineer Associate (AI-102)',
    provider: 'Microsoft',
    category: 'certificaciones',
    level: 'avanzado',
    price: 'pago',
    price_text: 'USD 165 aprox. el examen (varía por país); preparación gratuita en Microsoft Learn',
    has_certificate: true,
    language: 'es',
    url: 'https://learn.microsoft.com/es-es/credentials/certifications/azure-ai-engineer/',
    summary: 'Certificación para profesionales que diseñan e implementan soluciones de IA en Azure (visión, lenguaje, IA generativa y agentes). Requiere experiencia en programación.',
    tags: ['microsoft', 'azure', 'ai-102', 'certificación', 'desarrollo'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AWS Certified AI Practitioner (AIF-C01)',
    provider: 'AWS',
    category: 'certificaciones',
    level: 'principiante',
    price: 'pago',
    price_text: 'USD 100 aprox. el examen; preparación gratuita en AWS Skill Builder',
    has_certificate: true,
    language: 'es',
    url: 'https://aws.amazon.com/es/certification/certified-ai-practitioner/',
    summary: 'Certificación de nivel fundamental que valida conocimientos de IA, aprendizaje automático e IA generativa y sus casos de uso en AWS. Dirigida a perfiles técnicos y no técnicos; examen disponible en español.',
    tags: ['aws', 'aif-c01', 'certificación', 'ia generativa', 'español'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'AWS Artificial Intelligence Practitioner Learning Plan',
    provider: 'AWS',
    category: 'certificaciones',
    level: 'principiante',
    price: 'gratis',
    has_certificate: false,
    language: 'en',
    url: 'https://skillbuilder.aws/learning-plan/G8ENMJ5QBE/aws-artificial-intelligence-practitioner-learning-plan/SU2A1EJM1A',
    summary: 'Plan de aprendizaje gratuito de AWS Skill Builder que ordena los cursos digitales necesarios para preparar la certificación AWS Certified AI Practitioner.',
    tags: ['aws', 'aif-c01', 'preparación', 'skill builder'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Google Cloud Certified: Generative AI Leader',
    provider: 'Google Cloud',
    category: 'certificaciones',
    level: 'principiante',
    price: 'pago',
    price_text: 'USD 99 aprox. el examen; ruta de preparación gratuita',
    has_certificate: true,
    language: 'en',
    url: 'https://cloud.google.com/learn/certification/generative-ai-leader',
    summary: 'Certificación de Google Cloud para cualquier rol, sin requisitos técnicos, que valida conocimiento de negocio sobre cómo la IA generativa transforma organizaciones y sobre la oferta de IA de Google Cloud.',
    tags: ['google cloud', 'certificación', 'ia generativa', 'negocio'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Generative AI Leader – ruta de preparación',
    provider: 'Google Cloud',
    category: 'certificaciones',
    level: 'principiante',
    price: 'gratis',
    has_certificate: true,
    language: 'en',
    url: 'https://www.skills.google/paths/1951',
    summary: 'Ruta de cursos bajo demanda de Google Skills que prepara para la certificación Generative AI Leader, con práctica en Gemini, NotebookLM y Google AI Studio. Otorga insignias por curso.',
    tags: ['google cloud', 'preparación', 'ia generativa', 'insignia'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Google AI Professional Certificate',
    provider: 'Google',
    category: 'certificaciones',
    level: 'principiante',
    duration_text: '8 cursos de 1 hora aprox.',
    price: 'pago',
    price_text: 'USD 49/mes aprox. en Coursera (varía por país); incluye 3 meses de Google AI Pro',
    has_certificate: true,
    language: 'multi',
    url: 'https://grow.google/ai-professional/',
    summary: 'Certificado profesional de Google (8 cursos) que cubre fundamentos de IA y su uso para planificar, investigar, escribir, crear contenido, analizar datos y construir apps. Disponible en español y otros 15 idiomas.',
    tags: ['google', 'certificado profesional', 'coursera', 'español disponible'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Salesforce Certified AI Associate',
    provider: 'Salesforce',
    category: 'certificaciones',
    level: 'principiante',
    price: 'pago',
    price_text: 'USD 75 aprox. el examen; preparación gratuita en Trailhead',
    has_certificate: true,
    language: 'en',
    url: 'https://trailhead.salesforce.com/credentials/aiassociate',
    summary: 'Certificación de nivel inicial que valida conocimientos de IA, datos y uso ético de la IA en el contexto de Salesforce. Preparación gratuita mediante trails de Trailhead.',
    tags: ['salesforce', 'certificación', 'ia', 'trailhead'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Salesforce Certified Agentforce Specialist',
    provider: 'Salesforce',
    category: 'certificaciones',
    level: 'intermedio',
    price: 'pago',
    price_text: 'USD 200 aprox. el examen; preparación gratuita en Trailhead',
    has_certificate: true,
    language: 'en',
    url: 'https://trailhead.salesforce.com/credentials/agentforcespecialist',
    summary: 'Certificación para profesionales que configuran y optimizan agentes de IA con Agentforce, Prompt Builder y Data Cloud en Salesforce.',
    tags: ['salesforce', 'certificación', 'agentforce', 'agentes'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'NVIDIA-Certified Associate: Generative AI LLMs',
    provider: 'NVIDIA',
    category: 'certificaciones',
    level: 'intermedio',
    price: 'pago',
    price_text: 'USD 135 aprox. el examen',
    has_certificate: true,
    language: 'en',
    url: 'https://www.nvidia.com/en-us/learn/certification/generative-ai-llm-associate/',
    summary: 'Certificación de nivel asociado de NVIDIA que valida conocimientos fundamentales sobre IA generativa y modelos de lenguaje grandes, incluidos prompts, RAG y despliegue.',
    tags: ['nvidia', 'certificación', 'llm', 'ia generativa'],
    last_verified_at: '2026-09-05',
  },
  {
    title: 'Claude Certified Associate – Foundations',
    provider: 'Anthropic',
    category: 'certificaciones',
    level: 'principiante',
    price: 'pago',
    price_text: 'USD 99 el examen',
    has_certificate: true,
    language: 'en',
    url: 'https://anthropic-partners.skilljar.com/claude-certified-associate-foundations-certification',
    summary: 'Examen de certificación oficial de Anthropic que valida conocimientos fundamentales sobre Claude: capacidades, prompting y buenas prácticas de uso.',
    tags: ['anthropic', 'claude', 'certificación', 'skilljar'],
    last_verified_at: '2026-09-06',
  },
]
