create table public.trivia_questions (
  id bigint generated by default as identity primary key,
  month date not null check (month = date_trunc('month', month)::date),
  topic text not null,
  question text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  correct_option smallint not null check (correct_option between 0 and 3),
  explanation text not null,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  unique(month, sort_order)
);

alter table public.trivia_questions enable row level security;
revoke all on public.trivia_questions from anon, authenticated;
grant all on public.trivia_questions to service_role;
create index trivia_questions_month_sort on public.trivia_questions(month, sort_order);
